apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: helloworld
    service: frontend
    version: blue
    shard: blue
  name: frontend
  namespace: supreme-doodle
spec:
  replicas: 1
  selector:
    matchLabels:
      application: helloworld
      service: frontend
      version: blue
      shard: blue
  template:
    metadata:
      labels:
        application: helloworld
        service: frontend
        version: blue
        shard: blue
    spec:
      containers:
      - name: frontend
        # image: public.ecr.aws/z4m0n1r4/frontend
        image: ghcr.io/scrogatl/doodle-frontend:latest
        imagePullPolicy: Always
        env:
        - name: HELLO_HOST
          value: "hello"
          # value: "hello.demo.internal"
        - name: WORLD_HOST
          value: "world"
          # value: "world.demo.internal"
        - name: SHARD
          value: "blue"
        - name: PYTHONUNBUFFERED
          value: "1"
        ports:
        - containerPort: 5000
          name: application
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: supreme-doodle
spec: 
  selector:
    application: helloworld
    service: frontend  
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: doodle-frontend
  namespace: supreme-doodle
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /doodle
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 5000