apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: frontend-instance
    app.kubernetes.io/version: "0.9.1"
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: helloworld
    app.kubernetes.io/managed-by: helm
  name: frontend
  namespace: supreme-doodle
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/instance: frontend-instance
      app.kubernetes.io/version: "0.9.1"
      app.kubernetes.io/component: service
      app.kubernetes.io/part-of: helloworld
      app.kubernetes.io/managed-by: helm
  template:
    metadata:
      labels:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/instance: frontend-instance
      app.kubernetes.io/version: "0.9.1"
      app.kubernetes.io/component: service
      app.kubernetes.io/part-of: helloworld
      app.kubernetes.io/managed-by: helm
    spec:
      containers:
      - name: frontend
        # image: public.ecr.aws/z4m0n1r4/frontend
        image: ghcr.io/scrogatl/doodle-frontend:latest
        imagePullPolicy: Always
        env:
        - name: HELLO_HOST
          value: "hello"
        - name: WORLD_HOST
          value: "world"
        - name: WORLD_HOST_RUBY
          value: "world-ruby"
        - name: WPORT
          value: "80"
          # value: "5002"
        - name: WPORT_RUBY
          value: "5003"
        - name: SHARD
          value: "blue"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: DOODLE-VERSION
          value: "V0.99.4"
        - name: RUBY_WORLD
          value: "50"
        - name: NEW_RELIC_APP_NAME
          value: "doodle-frontend"
          - name: NEW_RELIC_LICENSE_KEY
          value:  "{{ .Values.nr_key }}"
        ports:
        - containerPort: 5000
          name: application
          protocol: TCP
