apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: supreme-doodle
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: frontend-instance
    app.kubernetes.io/version: "0.9.1"
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: helloworld
    app.kubernetes.io/managed-by: helm

spec: 
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: frontend-instance
    app.kubernetes.io/version: "0.9.1"
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: helloworld
    app.kubernetes.io/managed-by: helm
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
